import Head from "next/head";

export default function Terms() {
  const s = {
    page: { minHeight: "100vh", background: "#080b10", color: "#dde2ea", fontFamily: "'Segoe UI', sans-serif", padding: "0 16px 80px" },
    nav: { maxWidth: 720, margin: "0 auto", padding: "20px 0", display: "flex", justifyContent: "space-between", alignItems: "center", borderBottom: "1px solid rgba(255,255,255,0.05)" },
    logo: { fontSize: 16, fontWeight: 900, color: "#fff", textDecoration: "none" },
    back: { fontFamily: "monospace", fontSize: 11, color: "#445060", textDecoration: "none", letterSpacing: 1 },
    wrap: { maxWidth: 720, margin: "0 auto", paddingTop: 40 },
    tag: { display: "inline-block", fontFamily: "monospace", fontSize: 10, letterSpacing: 3, color: "#00ffe0", background: "rgba(0,255,224,0.06)", border: "1px solid rgba(0,255,224,0.18)", padding: "4px 12px", borderRadius: 3, marginBottom: 20 },
    h1: { fontSize: "clamp(22px,4vw,30px)", fontWeight: 900, color: "#fff", marginBottom: 8 },
    date: { fontFamily: "monospace", fontSize: 10, color: "#445060", letterSpacing: 2, marginBottom: 36 },
    h2: { fontSize: 16, fontWeight: 800, color: "#fff", marginTop: 32, marginBottom: 10 },
    p: { fontSize: 14, color: "#8899aa", lineHeight: 1.9, marginBottom: 14 },
    divider: { height: 1, background: "linear-gradient(90deg,transparent,rgba(255,255,255,0.07),transparent)", margin: "28px 0" },
    footer: { textAlign: "center", marginTop: 48, fontFamily: "monospace", fontSize: 10, color: "#2a3040", letterSpacing: 2 },
  };

  return (
    <>
      <Head>
        <title>Terms of Service — TruthScan AI</title>
        <meta name="description" content="Terms of Service for TruthScan AI. Rules and conditions for using our chat analysis service." />
        <link rel="canonical" href="https://truthscan.fun/terms" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <meta name="robots" content="noindex" />
        <meta name="theme-color" content="#00ffe0" />
      </Head>

      <style>{`* { box-sizing: border-box; margin: 0; padding: 0; } body { background: #080b10; }`}</style>

      <div style={s.page}>
        <nav style={s.nav}>
          <a href="/" style={s.logo}>TRUTH<span style={{ color: "#00ffe0" }}>SCAN</span></a>
          <a href="/" style={s.back}>← HOME</a>
        </nav>

        <div style={s.wrap}>
          <div style={s.tag}>📄 LEGAL</div>
          <h1 style={s.h1}>Terms of Service</h1>
          <div style={s.date}>LAST UPDATED: MARCH 2025 · TRUTHSCAN AI · INDIA</div>

          <p style={s.p}>By accessing or using TruthScan AI at truthscan.fun, you agree to these Terms of Service. If you do not agree, please do not use our service.</p>

          <div style={s.divider} />

          <h2 style={s.h2}>1. What TruthScan Is</h2>
          <p style={s.p}>TruthScan AI is an AI-powered chat analysis tool. You paste a conversation or upload a screenshot and our AI provides an analysis of emotional patterns, signals, and potential relationship dynamics.</p>
          <p style={s.p}><strong style={{ color: "#ff3d6e" }}>Important:</strong> TruthScan AI results are for entertainment and informational purposes only. They are generated by an AI model and should not be treated as professional psychological, legal, or relationship advice. We are not responsible for any decisions you make based on TruthScan results.</p>

          <div style={s.divider} />

          <h2 style={s.h2}>2. Eligibility</h2>
          <p style={s.p}>You must be at least 18 years old to use TruthScan. By using our service, you confirm that you meet this requirement.</p>

          <div style={s.divider} />

          <h2 style={s.h2}>3. Your Account</h2>
          <p style={s.p}>You are responsible for maintaining the security of your account. Do not share your login credentials with others. You are responsible for all activity that occurs under your account.</p>
          <p style={s.p}>We reserve the right to suspend or terminate accounts that violate these terms, engage in abuse, or attempt to misuse our service.</p>

          <div style={s.divider} />

          <h2 style={s.h2}>4. Credits and Payments</h2>
          <p style={s.p}>TruthScan operates on a credit system. Credits are purchased through Razorpay and are non-refundable once used. Unused credits do not expire and carry over indefinitely.</p>
          <p style={s.p}>All prices are in Indian Rupees (INR). We reserve the right to change pricing at any time. Existing purchased credits will not be affected by price changes.</p>
          <p style={s.p}>Each analysis deducts one credit from your balance. If an analysis fails due to a technical error on our end, your credit will be refunded automatically.</p>

          <div style={s.divider} />

          <h2 style={s.h2}>5. Acceptable Use</h2>
          <p style={s.p}>You agree not to use TruthScan to analyse conversations without the knowledge or consent of the other parties involved, for any illegal purpose, to harass, stalk, or harm any individual, or to attempt to reverse engineer, scrape, or exploit our service.</p>
          <p style={s.p}>We are not responsible for how you use the analysis results. You take full responsibility for your actions based on TruthScan output.</p>

          <div style={s.divider} />

          <h2 style={s.h2}>6. Content You Submit</h2>
          <p style={s.p}>By submitting chat content for analysis, you confirm that you have the right to share that content with our service. We process your content only to generate your analysis and do not claim ownership over it.</p>
          <p style={s.p}>Do not submit content containing sensitive personal information such as Aadhaar numbers, bank details, passwords, or other private data.</p>

          <div style={s.divider} />

          <h2 style={s.h2}>7. AI Limitations</h2>
          <p style={s.p}>TruthScan uses large language models to generate analysis. AI results can be inaccurate, incomplete, or misleading. The analysis represents a statistical pattern interpretation — not a definitive truth about any person or relationship. Always use your own judgement.</p>

          <div style={s.divider} />

          <h2 style={s.h2}>8. Service Availability</h2>
          <p style={s.p}>We aim to keep TruthScan available at all times but cannot guarantee uninterrupted service. We may perform maintenance, updates, or changes to the service at any time without notice.</p>

          <div style={s.divider} />

          <h2 style={s.h2}>9. Limitation of Liability</h2>
          <p style={s.p}>TruthScan AI and its creator are not liable for any direct, indirect, or consequential damages arising from your use of the service. This includes but is not limited to relationship decisions, emotional distress, or any outcomes resulting from acting on AI-generated analysis.</p>

          <div style={s.divider} />

          <h2 style={s.h2}>10. Governing Law</h2>
          <p style={s.p}>These terms are governed by the laws of India. Any disputes will be subject to the jurisdiction of courts in India.</p>

          <div style={s.divider} />

          <h2 style={s.h2}>11. Changes To These Terms</h2>
          <p style={s.p}>We may update these Terms of Service at any time. Updated terms will be posted on this page with a revised date. Continued use of TruthScan after changes means you accept the updated terms.</p>

          <div style={s.divider} />

          <h2 style={s.h2}>12. Contact</h2>
          <p style={s.p}>For any questions about these terms, contact us at <span style={{ color: "#00ffe0" }}>truthscan.fun@gmail.com</span>.</p>

          <div style={s.footer}>TRUTHSCAN AI · truthscan.fun · INDIA</div>
        </div>
      </div>
    </>
  );
}
